### DISCUSSION TITLE
Recommended server size to run Parca

### DISCUSSION THREAD

**Discussion by nabokihms** [parca-dev/parca#3921] [Q&A]
Hello, team! I have a question.

After completing the Kubernetes deployment guide, I now have an installation of Parca. For now, there are no agents, only two profile scrape sources configured manually.

![image](https://github.com/parca-dev/parca/assets/32434187/2ed6c94d-4b94-4bbc-8e6a-c7eb05eaa2c3)

Yet there is a problem that the memory consumption is growing infinitely until the pod is OOMkilled. 

https://pprof.me/4aae8e1/
![image](https://github.com/parca-dev/parca/assets/32434187/27a5f00d-fdb6-409d-a93e-bf2dc9317859)

So my question is: is everything OK? Do I need to give Parca more resources? Maybe I missed something.

**Comment by brancz** [comment]
Great question! Ultimately it really depends on your application, how many distinct stacks there are, how many and how long function names are, and so on, so this may be perfectly ok.

That said, I have a few recommendations:

* Update to v0.20.0 (which we just released an hour ago) which has a ton of memory improvements.
* I recommend dropping all memory profiling data except for memory heap. There are multiple reasons I say this:
  1) Memory in-use objects are rarely useful
  2) Memory-allocated objects and bytes are extremely expensive in their regular form, as they contain _all_ stacks since the beginning of the process that have ever allocated memory, the longer a process is alive the more extreme the amounts of data tend to get.

To keep only memory in-use bytes use this configuration on your scrape config:

```
      - job_name: parca
        scrape_interval: "10s"
        profiling_config:
          pprof_config:
            memory:
              keep_sample_type:
              - type: inuse_space
                unit: bytes
```

And last but not least, if possible (and we understand it's not necessarily always possible), use [Parca Agent](https://github.com/parca-dev/parca-agent) for CPU profiling, and turn off the in-process profilers from scraping using:

```
      - job_name: parca
        scrape_interval: "10s"
        profiling_config:
          pprof_config:
            process_cpu:
              enabled: false
```

In addition to that, you can tweak the active in-memory size allowed by the storage using the `--storage-active-memory` flag, which defaults to 512mb (and in v0.20.0 it's much more closely respected but there are still lots of improvements that it's actually close to identical but it's a knob you can tune down).
