### DISCUSSION TITLE
How to view off-cpu profile?

### DISCUSSION THREAD

**Discussion by ading1977** [parca-dev/parca#5576] [General]
I have built and deployed the `parca-agent` with the off-cpu profiling feature, and enabled that like the following:

```
      spec:
        containers:
        - args:
          - --http-address=:7071
          - --node=$(NODE_NAME)
          - --config-path=/etc/parca-agent/parca-agent.yaml
          - --remote-store-address=parca.parca.svc.cluster.local:7070
          - --remote-store-insecure
          - --off-cpu-threshold=30
```

How do I view my off-cpu profiling result in the parca server? On the server UI, I still only see the On-CPU profile type. Is the Off-CPU profiling supported in the server?

![image](https://github.com/user-attachments/assets/73ee8225-47d3-4542-830a-5822941da43e)
