### ISSUE TITLE
Disable allocs profile not working

### ISSUE THREAD

**Issue by syepes** [parca-dev/parca#1119]
Hello,

When trying to create a scrape job that only scrapes ones single profile like fgprof, it continues to scrape the `allocs` knowing that is was disabled.

Version: v0.11.1
With the following config we can reproduce the issue:

```
    - job_name: "kubernetes-pods-fgprof"
      scrape_interval: 30s
      scrape_timeout: 30s
      profiling_config:
        pprof_config:
          fgprof:
            path: /debug/fgprof
            enabled: true
          heap:
            enabled: false
          profile:
            enabled: false
          goroutine:
            enabled: false
          threadcreate:
            enabled: false
          allocs:
            enabled: false
          block:
            enabled: false
          mutex:
            enabled: false
          trace:
            enabled: false
```

This job should only scrape the fgprof profile.

Note: The disablement of all other profiles is working, its just `allocs` that is affected

**Comment by brancz** [comment]
Which version of Parca are you using?

**Comment by brancz** [comment]
Starting in 0.11.1 the config changed slightly, what you're looking for is:

```
    - job_name: "kubernetes-pods-fgprof"
      scrape_interval: 30s
      scrape_timeout: 30s
      profiling_config:
        pprof_config:
          fgprof:
            path: /debug/fgprof
            enabled: true
          memory:
            enabled: false
          process_cpu:
            enabled: false
          goroutine:
            enabled: false
          block:
            enabled: false
          mutex:
            enabled: false
```

Unfortunately we realized that there are a couple of problems in fgprof that actually make it impossible for us to scrape it as it has faulty data. We opened several PRs to fix that, but unfortunately not all are merged yet: https://github.com/felixge/fgprof/pulls?q=is%3Apr+author%3Abrancz+
