### ISSUE TITLE
CPU profile: timestamp column not found

### ISSUE THREAD

**Issue by marselester** [parca-dev/parca#1121]
Parca v0.11.1 returns `timestamp column not found` error when I try to query "Process CPU Samples" of a newly added Go app `B`. Memory profiles work ok though.

```
level=error name=parca ts=2022-06-03T15:02:34.475796457Z caller=logger.go:35 protocol=grpc grpc.component=server grpc.service=parca.query.v1alpha1.QueryService grpc.method=QueryRange grpc.method_type=unary grpc.start_time=2022-06-03T15:02:34Z grpc.code=Unknown grpc.error="timestamp column not found" grpc.time_ms=2.319 finishedcall=(MISSING)
```

The CPU profiles of an older Go app `A` are still shown properly.

**Comment by dogukanzorlu** [comment]
actually it's not a real error. When there is only one instance or job, if your query is equal to "not equal", you get a timestamp error because there is no label to show the result. Maybe They can show a better error message or add validation. :)

**Comment by marselester** [comment]
Interesting :) I get this error message when I filter by instance or by job of the app `B` (newly added). But there are no errors when filtering on the app `A` (old).

**Comment by dogukanzorlu** [comment]
as I said app B most likely has a single instance or single job. but still, for more accurate bug detection, it is useful to share your queries and target settings in a way that is safe for you.

**Comment by marselester** [comment]
Oh I see what you mean. BTW, both apps have single instance/job per app.

Queries with an error (APP_B):

```
https://parca.default/?currentProfileView=icicle&expression_a=process_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Binstance%3D%22APP_B.default%3A8081%22%7D&from_a=1654300487348&to_a=1654304087348&merge_a=false&time_selection_a=relative:hour|1
https://parca.default/?expression_a=process_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Bjob%3D%22APP_B%22%7D&from_a=1654300603268&to_a=1654304203268&merge_a=false&time_selection_a=relative:hour|1&currentProfileView=icicle
```

Queries without an error (APP_A):

```
https://parca.default/?currentProfileView=icicle&expression_a=process_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Binstance%3D%22APP_A.default%3A8080%22%7D&from_a=1654300668860&to_a=1654304268860&merge_a=false&time_selection_a=relative:hour|1
https://parca.default/?currentProfileView=icicle&expression_a=process_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Bjob%3D%22APP_A%22%7D&from_a=1654300774162&to_a=1654304374162&merge_a=false&time_selection_a=relative:hour|1
```

```yaml
debug_info:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"
  cache:
    type: "FILESYSTEM"
     config:
       directory: "./tmp"

scrape_configs:
  - job_name: "APP_A"
    scrape_interval: "5m"
    scrape_timeout: "10s"
    static_configs:
      - targets: [ 'APP_A.default:8080' ]
  - job_name: "APP_B"
    scrape_interval: "5m"
    scrape_timeout: "10s"
    static_configs:
      - targets: [ 'APP_B.default:8081' ]
```
