### ISSUE TITLE
path_prefix behaviour

### ISSUE THREAD

**Issue by wiardvanrij** [parca-dev/parca#1956]
I have a prometheus with a path, i.e. `foo.bar/prometheus` and tried to configure Parca with:

```
      - job_name: "prometheus"
        scrape_interval: "15s"
        static_configs:
          - targets: ['foo.bar.svc.cluster.local:9090']
        profiling_config:
          path_prefix: /prometheus
```

Which ignored the path prefix.

After I've configured it like:

```
      - job_name: "prometheus"
        scrape_interval: "15s"
        static_configs:
          - targets: ['foo.bar.svc.cluster.local:9090']
        profiling_config:
          path_prefix: /prometheus
          pprof_config:
            memory:
              enabled: true
              path: /debug/pprof/allocs
```

It's now scraping every profile. 

Would be nice if I can omit a default pprof_config and just only set path_prefix (and document this, I figured this out from your .go testing files :)
