### ISSUE TITLE
parca v0.15.0: scrape timeout must be greater than the interval

### ISSUE THREAD

**Issue by morremeyer** [parca-dev/parca#2332]
## Problem

With the upgrade to `v0.15.0`, parca does not start up for me anymore with the following error:

```
level=error name=parca ts=2022-12-22T17:17:37.560158972Z caller=parca.go:148 msg="failed to read config" path=/var/parca/parca.yaml
level=error name=parca ts=2022-12-22T17:17:37.56019391Z caller=main.go:59 msg="Program exited with error" err="parsing YAML file /var/parca/parca.yaml: scrape timeout must be greater than the interval: ez-backends"
```

The scrape config in question is:

```yaml
- job_name: "ez-backends"
  scrape_interval: 1m
  scrape_timeout: 45s
```

## Analysis 

While I do understand what the error means, I am confused by its existence.

Shouldn't the scrape timeout have to be *shorter* than the scrape interval, meaning that the error is the wrong way around right now?

Imagine the following config, which I just tested to work with `v0.15.0`:

```yaml
- job_name: "ez-backends"
  scrape_interval: 45s
  scrape_timeout: 1m
```

Times in minutes:seconds.

1. At 0:00, the first scrape starts
2. At 0:45, the second scrape starts
3. At 0:47, the second scrape is finished
4. At 0:55, the first scrape is finished

As far as I understand the order with which data should be written to the DB, this would be the wrong way around, which is why the scrape timeout would have to be shorter than the interval.

Happy about any input to clear up the confusion :)
