### ISSUE TITLE
Unable to query history when using S3 as persistent storage

### ISSUE THREAD

**Issue by gites** [parca-dev/parca#2711]
I'm unable to query history for more then 15 minutes when using S3 as persistent storage.  I'm getting "Access denied" message in the UI. The `stacktraces`  are  showing up in S3 bucket. 

Parca daemon logs are reporting this:
```
{"caller":"logger.go:38","finished call":"(MISSING)","grpc.code":"Unknown","grpc.component":"server","grpc.error":"failed to convert row group to arrow record: convert parquet column to arrow array: read page: Access Denied","grpc.method":"QueryRange","grpc.method_type":"unary","grpc.service":"parca.query.v1alpha1.QueryService","grpc.start_time":"2023-03-08T14:19:38Z","grpc.time_ms":"8222.809","level":"error","name":"parca","peer.address":"127.0.0.1:35720","protocol":"grpc","ts":"2023-03-08T14:19:46.245544768Z"}
```
When I switch back to filesystem based storage there is no such problem.

Strorage config:
```
   object_storage:
      bucket:
        type: s3
        config:
          bucket: some-bucket
          endpoint: s3.us-west-2.amazonaws.com
          region: us-west-2
          insecure: false
          signature_version2: false
```

**Comment by gites** [comment]
I don't use the official Parca Helm chart. The IAM settings on the deployment where ok, but inspired by your comment I dig a bit deeper and manage to fix the problem by adding  `aws_sdk_auth: true` to the object store configuration.
The working config looks like this: 
```
   object_storage:
      bucket:
        type: s3
        config:
          aws_sdk_auth: true
          bucket: some-bucket
          endpoint: s3.us-west-2.amazonaws.com
          region: us-west-2
          insecure: false
          signature_version2: false
```
