### ISSUE TITLE
Parca reporting Invalid magic footer of parquet file

### ISSUE THREAD

**Issue by gites** [parca-dev/parca#2712]
I deployed Parca 0.16.2 to my environment and starting scraping pprof data from a bunch of golang services.
After flew hour Parca UI is reporting error: `Error! invalid magic footer of parquet file:`
Parca daemon logs:
```
{"caller":"logger.go:38","finished call":"(MISSING)","grpc.code":"Unknown","grpc.component":"server","grpc.error":"invalid magic footer of parquet file: \"q8rE\"","grpc.method":"ProfileTypes","grpc.method_type":"unary","grpc.service":"parca.query.v1alpha1.QueryService","grpc.start_time":"2023-03-08T17:09:59Z","grpc.time_ms":"33.242","level":"error","name":"parca","peer.address":"127.0.0.1:41238","protocol":"grpc","ts":"2023-03-08T17:09:59.750457908Z"}
```
After I restarted the Parca daemon:
```
{"caller":"logger.go:38","finished call":"(MISSING)","grpc.code":"Unknown","grpc.component":"server","grpc.error":"invalid magic footer of parquet file: \"\\x01`\\xae*\"","grpc.method":"ProfileTypes","grpc.method_type":"unary","grpc.service":"parca.query.v1alpha1.QueryService","grpc.start_time":"2023-03-08T17:13:22Z","grpc.time_ms":"4.646","level":"error","name":"parca","peer.address":"127.0.0.1:46272","protocol":"grpc","ts":"2023-03-08T17:13:22.827904475Z"}
```

Parca options:
```
        - /parca
        - --config-path=/etc/parca/parca.yaml
        - --cors-allowed-origins=*
        - --enable-persistence
        - --storage-path=/parca-storage
        - --log-format=json
        - --insecure
 ```
Config:
```yaml
object_storage:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: /parca-storage

scrape_configs:
  - job_name: some-name
    scrape_interval: "1m"
    scrape_timeout: "90s"
    static_configs:
      - targets: ["172.18.173.199:4443"]
    scheme: https
    tls_config:
      ca_file: /my-ca-root.pem
    relabel_configs:
    - target_label: pod
      replacement: some-name
    - target_label: namespace
      replacement: some-name
    - target_label: deployment
      replacement: some-deployment
    - target_label: job
      replacement: some-name
    - target_label: ip
      replacement: 172.18.173.199
    - target_label: port
      replacement: 4443

#  - job_name: some-name2
#  [more jobs]
```
