### ISSUE TITLE
Scrape config group labels aren't added to targets

### ISSUE THREAD

**Issue by thorfour** [parca-dev/parca#2742]
If you add a set of group labels to a static config (presumable any scrape config type) such as 
```
scrape_configs:
  - job_name: "parca"
    scrape_interval: "3s"
    static_configs:
      - targets: [ '127.0.0.1:7070' ]
      - labels:
             hello: "world"
```

Those labels do not show up for any of the targets, it seems they aren't being passed into the targets.

**Comment by maxbrunet** [comment]
Could it be a typo?

```diff
 scrape_configs:
   - job_name: "parca"
     scrape_interval: "3s"
     static_configs:
       - targets: [ '127.0.0.1:7070' ]
-      - labels:
+        labels:
              hello: "world"
```

**Comment by maxbrunet** [comment]
Maybe I misunderstood the issue, you would like these lone labels to be passed to all targets?
At moment, I think I would use `external_labels` (all targets in all jobs) or `relabel_configs` (all targets in a job) to achieve that.

**Comment by thorfour** [comment]
That's interesting, because when some debug prints I found that the config parsed the `-labels` as the group labels, but it wasn't passing it through. If it's a typo then we can close this 👍 I just found the behavior odd since it "almost" worked correctly

**Comment by maxbrunet** [comment]
The config is equivalent to:

```yaml
scrape_configs:
  - job_name: "parca"
    scrape_interval: "3s"
    static_configs:
      - targets: [ '127.0.0.1:7070' ]
      - targets: null
        labels:
             hello: "world"
```

So when the scraper configure the targets, it likely uses `range` on them and this one is empty, so nothing happens, maybe we could warn when it is `nil`, but some discoveries might return that when no target is found
