### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by paulfantom** [parca-dev/parca#301]
I got quite high memory usage from parca (~45GB) and parca-agent (~1GB). This is on a one node setup without any additional scrape_configs. Node has just 44 pods running.

parca pprof from heap - https://share.polarsignals.com/f8b0beb/
parca-agent pprof from heap - https://share.polarsignals.com/89d4e84/

Might be related to https://github.com/parca-dev/parca/issues/283 but I did not have time to investigate.

**Comment by metalmatze** [comment]
For now, I'd recommend running Parca with retention of a few hours 3h, 6h, 12h, depending on what you're willing to pay for in terms of memory. 
Chunks older than the retention are emptied and reused for newer chunks. This should make things more predictable for now.

**Comment by metalmatze** [comment]
The one thing that definitely still keeps increasing with no vacuuming happening is metadata. 
So if you have a lot of churns (maybe you have many deployments happening, etc) then this is right now ever so slightly increasing.
Other than that it should be running mostly stable. At least that's the case for https://demo.parca.dev 

Could you check the `/metrics` endpoint of Parca see if you can observe an increase of truncated chunks over time?
The metric to look for is `parca_tsdb_head_truncated_chunks_total`. Another one would be `parca_tsdb_head_min_time` and seeing if that increases ever so slightly after the oldest chunks are truncated too. Let us know!

**Comment by avestuk** [comment]
This is a graph from this morning 

![image](https://user-images.githubusercontent.com/28152118/159890226-7c3d2d5b-f67a-4af8-bd70-42808e4a536c.png)

**Comment by brancz** [comment]
Hey all. We've landed the new and improved storage in `main`. You can try a latest image (like `ghcr.io/parca-dev/parca:main-ddad21cc`), and enable the new storage with `--storage=columnstore`. Would love to see how it performs for you! Note that currently the column-store will accumulate 512mb of memory and then throw away all data and start over. The amount can be controlled with `--storage-active-memory=536870912`. We're still working on persisting the data.

**Comment by PhilipGough** [comment]
@brancz just weighing in on this with what I have observed running `v0.12.0` as it may be helpful.

Heres the relevant config:

```yaml
  containers:
    - resources:
        limits:
          cpu: '8'
          memory: 32Gi
        requests:
          cpu: '2'
          memory: 8Gi
      image: 'quay.io/observatorium/parca:v0.12.0'
      args:
        - /parca
        - '--config-path=/var/parca/parca.yaml'
        - '--log-level=info'
        - '--storage-active-memory=20000000000'       
```

And a graph of the memory usage:

<img width="1915" alt="Screenshot 2022-07-22 at 15 48 41" src="https://user-images.githubusercontent.com/5781491/180465252-657f9014-499e-46fa-bcda-22f5ba102a5e.png">

It didn't OOM so I expect there was some rotation when `storage-active-memory` was reached.
I just wanted to clarify if the behaviour looks ok up until that point though? Memory usage seems to steadily increase and we are scraping ~20 static (no churn) Pods as targets.
