### ISSUE TITLE
Data disappeared after pod restart with Google Storage Bucket

### ISSUE THREAD

**Issue by edmeister** [parca-dev/parca#3048]
I'm setting up Parca for a POC, using the official Helm chart. I have configured a Google Storage Bucket for persistence, and I can tell the bucket is actually being used. So far, so good. 

However, when the pod is restarted because of a change in configuration, I notice the data from before the restart is no longer retrieved from the UI when running search, although it still appears to be in the bucket.

The relevant part of my Helm values file looks like this: (the variables are terraform templating)
```yaml
server:
  config:
    object_storage:
      bucket:
        type: GCS
        config:
          bucket: ${bucket}
          service_account: ${gcpServiceAccount}
        prefix: "/parca"
```
This is rendered in `/var/parca/parca.yaml` as this:
```
object_storage:
  bucket:
    config:
      bucket: my-redacted-bucket
      directory: ./tmp
      service_account: |
        {
          "type": "service_account",
          ...
        }
    prefix: /parca
    type: GCS
```

Is something wrong or missing in my config or is this a known issue? Thanks for helping out!
