### ISSUE TITLE
Document Contour HTTPProxy workaround

### ISSUE THREAD

**Issue by jzelinskie** [parca-dev/parca#3419]
Hey there folks!

Contour does not any configuration to disable [Envoy's functionality that converts grpc-web into gRPC](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc#grpc-bridging).

You can track this issue upstream here: https://github.com/projectcontour/contour/issues/4290

It took a little bit of a workaround to things working, but ultimately this should do the trick:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
...
spec:
  routes:
  - conditions:
    - prefix: /api/
    pathRewritePolicy:
      replacePrefix:
      - replacement: /
    services:
    - name: parca
      port: 7070
      protocol: h2c
  - services:
    - name: parca
      port: 7070
  ...
```

This allows the conversion to gRPC to take place and then rewrites the URL so that Parca's gRPC endpoint (which is at `/` and not `/api`) receives it.
