### ISSUE TITLE
Failed to load latest snapshot

### ISSUE THREAD

**Issue by ricoberger** [parca-dev/parca#3430]
Hi, we are currently trying out Parca, so maybe this is related to some misconfiguration. Our deployment for Parca looks as follows:

<details>
<summary>StatefulSet</summary>

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: parca-server
  name: parca-server
  namespace: profiling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parca-server
  template:
    metadata:
      labels:
        app: parca-server
    spec:
      imagePullSecrets:
        - name: staffbase-artifactory
      containers:
        - args:
            - /parca
            - --http-address=:7070
            - --config-path=/etc/parca/parca.yaml
            - --log-level=info
            - --log-format=json
            - --cors-allowed-origins=*
            - --debuginfod-upstream-servers=https://debuginfod.systemtap.org
            - --debuginfod-http-request-timeout=5m
            - --enable-persistence
            - --storage-enable-wal
            - --storage-path=/data/storage
          image: ghcr.io/parca-dev/parca:v0.18.0
          livenessProbe:
            exec:
              command:
                - /grpc_health_probe
                - -v
                - -addr=:7070
            initialDelaySeconds: 5
          name: parca
          ports:
            - containerPort: 7070
              name: http
          readinessProbe:
            exec:
              command:
                - /grpc_health_probe
                - -v
                - -addr=:7070
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/parca
              name: config
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 120
      volumes:
        - secret:
            secretName: parca-server
          name: config
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: managed-premium
```

</details>

<details>
<summary>parca.yaml</summary>

```yaml
object_storage:
  bucket:
    config:
      directory: /data/object_storage
    type: FILESYSTEM
```

</details>

Our setup was working for the last 24h, but after the latest restart, Parca is not able to start anymore, with a `failed to load latest snapshot` error message. The complete logs are looking as follows:

```
{"caller":"factory.go:54","level":"info","msg":"loading bucket configuration","name":"parca","ts":"2023-07-11T07:41:38.984105843Z"}
{"caller":"badger.go:54","level":"info","msg":"All 38 tables opened in 1ms\n","name":"parca","ts":"2023-07-11T07:41:38.991914581Z"}
{"caller":"badger.go:54","level":"info","msg":"Discard stats nextEmptySlot: 0\n","name":"parca","ts":"2023-07-11T07:41:38.994221762Z"}
{"caller":"badger.go:54","level":"info","msg":"Set nextTxnTs to 47584","name":"parca","ts":"2023-07-11T07:41:38.994291479Z"}
{"caller":"badger.go:54","level":"info","msg":"Deleting empty file: /data/storage/metastore/000025.vlog","name":"parca","ts":"2023-07-11T07:41:38.994409426Z"}
{"caller":"db.go:495","db":"parca","level":"info","msg":"recovering db","name":"parca","ts":"2023-07-11T07:41:38.997660795Z"}
{"caller":"db.go:502","db":"parca","err":"no valid snapshots found","level":"info","msg":"failed to load latest snapshot","name":"parca","ts":"2023-07-11T07:41:38.997698085Z"}
```
