### ISSUE TITLE
Problem with Scrape Timeout and Scrape Interval

### ISSUE THREAD

**Issue by ricoberger** [parca-dev/parca#3436]
Hi and sorry for opening another issue, but I think there is sth. wrong with the scrape timeout and scrape interval.

In the [documentation](https://www.parca.dev/docs/ingestion#alternative-approaches) there is an example where the scrape timeout and interval is set:

```yaml
scrape_configs:
  - job_name: "default"
    scrape_interval: "60s"
    scrape_timeout: "45s"
    static_configs:
      - targets: [ '127.0.0.1:7070' ]
```

In the example the scrape interval is larger then the scrape timeout, but while the configuration is loaded there is a check that the timeout is larger then the interval: https://github.com/parca-dev/parca/blob/09c8abda89eaa5dede779b05e458cc23309326ce/pkg/config/config.go#L262-L264

Should this really be the case or is this just a mistake in the documentation. Coming from Prometheus I think the scrape timeout must always be smaller then the scrape interval?
