### ISSUE TITLE
No long-term profiles visible: invalid magic footer of parquet file

### ISSUE THREAD

**Issue by niaurys** [parca-dev/parca#4162]
We are running Parca 0.19.0, but after a few hours (or a day, I have no exact time sadly), we are not able to see any profiles with the following error in UI:

<img width="467" alt="image" src="https://github.com/parca-dev/parca/assets/61086968/0402a668-900b-4e3e-ab15-5a9c522283fb">

The same error is seen in the logs:
```
Nov 28 10:27:25 <> parca[1223890]: level=error name=parca ts=2023-11-28T10:27:25.641016727Z caller=server.go:320 msg="finished call" protocol=grpc grpc.component=server grpc.service=parca.query.v1alpha1.QueryService grpc.method=ProfileTypes grpc.method_type=unary peer.address=10.33.17.37:50402 grpc.start_time=2023-11-28T10:27:24Z grpc.code=Unknown grpc.error="invalid magic footer of parquet file: \"\\xfd\\xf4Ŭ\"" grpc.time_ms=689.939
```

Parca is deployed to the physical server and launched as SystemD service:

```
[Unit]
Description=Parca server service
After=network.target

[Service]
ExecStart=/opt/parca/parca --http-address=10.34.7.35:7070 --config-path=/opt/parca/parca.yaml --log-level=info --storage-granule-size=26265625 --storage-active-memory=53687091200 --enable-persistence --storage-path=/opt/parca/data
LimitNOFILE=65536
User=parca
Group=parca
Restart=always
WorkingDirectory=/opt/parca

[Install]
WantedBy=multi-user.target
```

Parca itself is configured to discover targets via Consul and Kube API (2 jobs) for pulling profile data and has persistent S3 storage (Ceph) with the following config:

```
object_storage:
  bucket:
    type: S3
    config:
      endpoint: 127.0.0.1:7481
      insecure: true
      signature_version2: false
      bucket: parca
      access_key: <..>
      secret_key: <..>
scrape_configs:
- job_name: default
  scrape_interval: 30s
  relabel_configs:
  - source_labels:
    - __meta_consul_service
    target_label: job
  - source_labels:
    - __meta_consul_node
    - __meta_consul_service_port
    target_label: instance
    action: replace
    regex: "^(.+);(\\d+$)"
    replacement: "${1}:${2}"
  - source_labels:
    - __meta_consul_service
    target_label: service
    action: replace
  - source_labels:
    - __meta_consul_node
    target_label: hostname
    action: replace
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){0}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){1}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){2}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){3}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){4}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){5}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){6}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    action: replace
    regex: ",(?:[^,]+,){7}([^=]+)=([^,]+),.*"
    replacement: "${2}"
    target_label: "${1}"
  - source_labels:
    - __meta_consul_tags
    target_label: service
    action: replace
    regex: ".*,backstage_service=([^,]+),.*"
    replacement: "$1"
  - action: labeldrop
    regex: backstage_service
  consul_sd_configs:
  - server: 127.0.0.1:8500
    services:
    - thanos-sandbox-compactor
    - thanos-sandbox-core-store
    - thanos-sandbox-ext-receive-ingester-metrics
    - thanos-sandbox-ext-receive-router-metrics
    - thanos-sandbox-int-core-receive-ingester-metrics
    - thanos-sandbox-int-core-receive-router-metrics
    - thanos-sandbox-int-receive-ingester-metrics
    - thanos-sandbox-int-receive-router-metrics
    - thanos-sandbox-query-global
    - thanos-sandbox-query-regional
    - thanos-sandbox-query-ruler-global
    - thanos-sandbox-query-ruler-regional
    - thanos-sandbox-query-ruler-regional-global
    - thanos-sandbox-queryfrontend
    - thanos-sandbox-queryfrontend-global
    - thanos-sandbox-ruler
    - thanos-sandbox-ruler-global
    - thanos-sandbox-sidecar
  profiling_config:
    pprof_config:
      memory:
        enabled: true
        path: "/debug/pprof/allocs"
      block:
        enabled: false
        path: "/debug/pprof/block"
      cmdline:
        enabled: false
        path: "/debug/pprof/cmdline"
      goroutine:
        enabled: true
        path: "/debug/pprof/goroutine"
      heap:
        enabled: true
        path: "/debug/pprof/heap"
      mutex:
        enabled: false
        path: "/debug/pprof/mutex"
      process_cpu:
        enabled: true
        delta: true
        path: "/debug/pprof/profile"
      thread_create:
        enabled: true
        path: "/debug/pprof/threadcreate"
- job_name: k8s_pod_infra1
  scrape_interval:
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_phase
    action: drop
    regex: Succeeded|Failed
  - source_labels:
    - __meta_kubernetes_pod_container_init
    regex: 'true'
    action: drop
  - source_labels:
    - __meta_kubernetes_pod_annotation_parca_dev_scrape
    regex: 'true'
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    action: replace
    target_label: service
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_label_app
    action: replace
    separator: "/"
    target_label: job
    replacement: "$1"
  - source_labels:
    - __meta_kubernetes_namespace
    action: replace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_name
    action: replace
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_container_name
    action: replace
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_node_name
    action: replace
    target_label: hostname
    replacement: "${1}"
  - action: replace
    target_label: cluster
    replacement: infra1
  - source_labels:
    - __meta_kubernetes_pod_name
    - __meta_kubernetes_pod_container_name
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    action: replace
    separator: ":"
    target_label: instance
  kubernetes_sd_configs:
  - api_server: https://infra1.kube-apiserver.service.consul:6443
    tls_config:
      insecure_skip_verify: true
    bearer_token: <...>
    role: pod
  profiling_config:
    pprof_config:
      memory:
        enabled: true
        path: "/debug/pprof/allocs"
      block:
        enabled: false
        path: "/debug/pprof/block"
      cmdline:
        enabled: false
        path: "/debug/pprof/cmdline"
      goroutine:
        enabled: true
        path: "/debug/pprof/goroutine"
      heap:
        enabled: true
        path: "/debug/pprof/heap"
      mutex:
        enabled: false
        path: "/debug/pprof/mutex"
      process_cpu:
        enabled: true
        delta: true
        path: "/debug/pprof/profile"
      thread_create:
        enabled: true
        path: "/debug/pprof/threadcreate"
```

Parquet files are saved correctly on bucket it seems:

```
s3cmd ls s3://parca/blocks/parca/stacktraces/
                          DIR  s3://parca/blocks/parca/stacktraces/01HEMD5DEKPNRWQ7NMAPTM9QXF/
                          DIR  s3://parca/blocks/parca/stacktraces/01HEN20KKV3ZW0GTJHDZCDP1Q8/
                          DIR  s3://parca/blocks/parca/stacktraces/01HENPHQ3G2AHV1V5W3QMDJ7Y5/
                          DIR  s3://parca/blocks/parca/stacktraces/01HEPAT2YZP1G0YXA3PJMS0Q7X/
                          DIR  s3://parca/blocks/parca/stacktraces/01HEPYXRQB4WSQ900WVVMKJ9P3/
<...>
```

Version info:
```
/opt/parca/parca --version
parca, version 0.19.0 (commit: 302a1927f96eb0467efcffd61b7d268ed4724b07)
```

Found related issue: https://github.com/parca-dev/parca/issues/2712, however, we do not have `FILESYSTEM` as backing storage, so should not be related.

What can be the problem with our setup? Is there any way to solve the issue?

Let me know in case you need more information.
