### ISSUE TITLE
question: why can not see memory in use profile?

### ISSUE THREAD

**Issue by withlin** [parca-dev/parca#523]
i see the docs,which have some profile,eg: heap_inuse_space, heap_inuse_object

![image](https://user-images.githubusercontent.com/22409551/148355396-7702a9cb-f502-46fe-81eb-9150a3a6324b.png)

but i am only see cpu profile
![image](https://user-images.githubusercontent.com/22409551/148355675-c9590694-6642-4ec8-a388-0dd584613939.png)

so what should i do?

**Comment by yeya24** [comment]
@withlin If you are using the parca agent now then I think only CPU profile are supported.
You can use the pull model to scrape profiles. This is the same as conprof and very similar to Promethues.

**Comment by withlin** [comment]
@yeya24 yes, i am use  the parca agent.  the parca agent use ebpf,which not support memory collect?

>You can use the pull model to scrape profiles. This is the same as conprof and very similar to Promethues.

thank you very much.

**Comment by yeya24** [comment]
@withlin AFAIK, heap profile is not supported by the agent. The pull model works by pulling profiles from /debug/pprof/* endpoints.

You can use the config like below, or simply use other SD you want like k8s.
```
debug_info:
  bucket:
    config:
      directory: './tmp'
    type: FILESYSTEM
  cache:
    config:
      directory: './tmp'
    type: FILESYSTEM
scrape_configs:
- job_name: 'pprof-example-app-go'
  scrape_interval: 1m
  scrape_timeout: 1m
  static_configs:
  - targets: ['localhost:8080']
```

At the mean time, although the parca agent is more recommended to use Parca, I feel it is important to have more documentation for the pull model, too.
