### ISSUE TITLE
Permission Error After Enabling Persistence in Parca StatefulSet

### ISSUE THREAD

**Issue by Chinnam08** [parca-dev/parca#5368]
We have been using [parca-dev/helm-charts](https://github.com/parca-dev/helm-charts) for several months with the standard Deployment configuration, and everything has been working fine. Recently, we decided to enable persistence for the Parca server by adding the `--enable-persistence` flag. To achieve this, we replaced the Deployment with a StatefulSet and added a PersistentVolumeClaim. However, after making these changes, we started encountering a permission error.

```
volumeClaimTemplates:
- metadata:
     name: parca-storage
  spec:
     accessModes: [ "ReadWriteOnce" ]
     storageClassName: gp2-encrypted
      resources:
         requests:
         storage: 8Gi
```
```
           args:
              - /parca
              - --config-path=/var/parca/parca.yaml
              - --log-level=info
              - --cors-allowed-origins=*
              - --enable-persistence=true
             - --storage-path=/var/lib/parca
              - --storage-active-memory=2147483648
```

`level=error name=parca ts=2024-11-14T04:58:34.983272541Z caller=main.go:66 msg="Program exited with error" err="Error Creating Dir: \"/data/metastore\" error: mkdir /data/metastore: permission denied"`

It seems like Parca is unable to create the necessary directories due to permission issues, even though the StatefulSet and volume mounts appear to be configured correctly.

We followed the steps in issues like [#3048](https://github.com/parca-dev/parca/issues/3048), but we are still facing the permission issue.

We have tried adjusting the fsGroup, runAsUser, and runAsGroup in the securityContext, but it did not resolve the issue.

Could you please assist us in resolving this issue? Any guidance on how to fix the permissions would be greatly appreciated
