### ISSUE TITLE
Parca server memory increasing indefinitely

### ISSUE THREAD

**Issue by doron-cohen** [parca-dev/parca#5605]
Hey, We are evaluating Parca to provide better observability over resources in our clusters. It is straightforward and does the job so thanks for working on this!

I do find getting it to work correctly a little confusing. At first all data was deleted on restart which we solved with a PVC and the `--enable-persistence` flag. This works great but we still see memory is rising across time indefinitely. We got to 1GiB and increasing only gets it to work a little bit more before crashing on OOM.

I tried a few configuration options and wonder if I am missing something. Attaching our current Helm values (we only use the server and probe pprof endpoints) and graph of memory. Notice how sometimes the pod would deploy, load the WAL dump from disk and crash instantly.

```yaml
parca:
  agent:
    # -- We don't need the agent since we are monitoring Go services only for now
    enabled: false

  server:
    # -- Allows disabling parca server
    enabled: true
    image:
      # -- Overrides the image repository for server
      repository: ghcr.io/parca-dev/parca
      # -- Overrides pull policy for server
      pullPolicy: IfNotPresent
      # -- Overrides the image tag for server
      tag: "v0.20.0"
    # -- extra containers (e.g: auth proxy)
    extraContainers: []
    # -- logging level of parca server
    logLevel: info
    # -- Active memory dedicated for storage. 256mb
    storageActiveMemory: 268435456

    extraArgs:
      - --enable-persistence
      - --storage-enable-wal
      - --storage-snapshot-trigger-size=67108864
      - --storage-path=/data

    extraVolumes:
      - name: parca-data
        persistentVolumeClaim:
          claimName: parca-pvc

    extraVolumeMounts:
      - name: parca-data
        mountPath: /data

    # -- Add security context to manage volume permissions
    podSecurityContext:
      # -- Run as nobody user to avoid permission issues
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

    # -- parca server config block
    config:
      object_storage:
        bucket:
          type: "FILESYSTEM"
          config:
            directory: "/data"

    # -- scrape configs for parca server
    scrapeConfigs:
      - job_name: 'kubernetes-pods'
        scrape_interval: 1m
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_parca_dev_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_parca_dev_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_parca_dev_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 500m
        memory: 1024Mi
```

Some notes which I think might improve deployment and starting up with the service / Helm chart:
1. There are a lot of values to get correct (`storageActiveMemory`, `--storage-snapshot-trigger-size`, etc). Maybe some options should be combined?
2. I really struggled with `podSecurityContext`. It is a must AFAIU since the container user is `nobody`. Worth documenting it.

I am aware of #301 but I thought there might be something else since it looks like it was resolved back then.

Thanks!

**Comment by doron-cohen** [comment]
Updating that I might have reached some solution as it is running stable on about 500MiB memory consumption with the following configuration:
```yaml
    storageActiveMemory: 536870912

    extraArgs:
      - --enable-persistence
      - --storage-enable-wal
      - --storage-snapshot-trigger-size=134217728
      - --storage-path=/data
      - --storage-index-on-disk
```

I believe `--storage-index-on-disk` is the thing that solved it. I really hope this was documented better or had saner defaults.
What do you think about enabling index on disk by default when enabling persistance?
