### ISSUE TITLE
Grpc requires http/2%0a

### ISSUE THREAD

**Issue by rgarrigue** [parca-dev/parca#5645]
Hello,

I just deployed parca server in my IT cluster and agent in the other cluster where we want to profile stuff to find more about memory leaks. Using the Helm chart. Trying to reach the UI I get this `Grpc requires http/2%0a` 

![Image](https://github.com/user-attachments/assets/d86f962f-d1f6-422e-8df4-57017b1de7a6)

It ain't my first gRPC app, so I added the service annotation relevant to my ingress controller, projectcontour.io. Checked with a call to a randm /thisisatest, I do see the protocol HTTP/2. Still doesn't work for Parca server UI

``` 
contour-envoy-85w52 envoy {"@timestamp":"2025-05-28T09:24:23.281Z","path":"/thisisatest","requested_server_name":"profiles.company.cloud","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","upstream_service_time":"0","request_id":"2ad8f2eb-8ff9-4557-9099-c171ae3e9038","duration":1,"downstream_remote_address":"_______:36552","bytes_sent":479,"x_forwarded_for":"_______","upstream_cluster":"parca_parca-server-server_7070","method":"GET","upstream_host":"10.2.11.101:7070","protocol":"HTTP/2","downstream_local_address":"10.2.11.91:8443","response_flags":"-","bytes_received":0,"authority":"profiles.company.cloud","upstream_local_address":"10.2.11.91:59620","response_code":200}
```

So wondering if there's anything more to this gRPC requirement regarding parca ?

**Comment by rgarrigue** [comment]
Indeed, the suggested workaround fixed it. Thanks ! 🙏🏿 

Note that I'd suggest adding to parca's chart templates/ folder a "extraManifests.yaml"  with something like

```
{{ range $k, $manifest := .Values.extraManifests }}
---
# $k
{{ tpl (toYaml $manifest) $ }}
{{ end }}
```

To let one add an httproxy in the values.yaml

```
manifests:
  httpproxy:
    apiVersion: projectcontour.io/v1
    kind: HTTPProxy
    metadata:
      name: parca-server
    spec:
      routes:
        - conditions:
            - prefix: /api/
          pathRewritePolicy:
            replacePrefix:
              - replacement: /
          services:
            - name: parca-server-server
              port: 7070
              protocol: h2c
        - services:
            - name: parca-server-server
              port: 7070
      virtualhost:
        fqdn: profiles.example.com
        tls:
          secretName: parca-server-tls
  certificate:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: parca-server-tls
    spec:
      commonName: profiles.example.com
      dnsNames:
        - profiles.example.com
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: parca-server-tls
```
