### ISSUE TITLE
Duplicate namespace in kubernetes-manifest.yaml 

### ISSUE THREAD

**Issue by marselester** [parca-dev/parca#871]
I noticed that there is a duplicate definition of the namespace in https://github.com/parca-dev/parca/releases/download/v0.10.0/kubernetes-manifest.yaml (line 2 and 97).

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: parca
```
