### ISSUE TITLE
Parca starts with invalid config

### ISSUE THREAD

**Issue by roidelapluie** [parca-dev/parca#929]
Parca 0.10.0

When trying to setup Parca, I noticed that it does start even with invalid yaml fields.

it would be helpful if parca refused to start if provided with an invalid configuration.

In my example parca started with the following invalid config (insecure vs insecure_skip_verify):

```
scrape_configs:                      
  - job_name: "pr"          
    scrape_interval: "3s"                                                  
    scrape_timeout: "2s"
    scheme: https
    tls_config:                      
            insecure: true   
```
