### ISSUE TITLE
Document profiling_config

### ISSUE THREAD

**Issue by roidelapluie** [parca-dev/parca#930]
While parca is mostly configured like prometheus, I could not find documentation about profiling_config.

This was needed to configure Parca for prometheus' prombench, which requires prefixes.

```
scrape_configs:                      
  - job_name: "pr"          
    scrape_interval: "3s"                                                  
    scrape_timeout: "2s"
    scheme: https                    
    profiling_config:                                                      
      pprof_config:
       memory_total:        
               enabled: true                                               
               path: /10543/prometheus-pr/debug/pprof/allocs               
       block_total:         
               enabled: true                                               
               path: /10543/prometheus-pr/debug/pprof/block                
       goroutine_total:              
               enabled: true                                               
               path: /10543/prometheus-pr/debug/pprof/goroutine            
       mutex_total:                                                        
               enabled: true
               path: /10543/prometheus-pr/debug/pprof/mutex                
       process_cpu:                                                        
               enabled: true
               path: /10543/prometheus-pr/debug/pprof/profile              
               delta: true
    tls_config:                      
            insecure_skip_verify: true                                     
    static_configs:
      - targets: [ 'prombench.prometheus.io' ]                             
```
