### ISSUE TITLE
document how to add an additional pprof scrape endpoint

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#986]
While Parca is capable of this, it is nowhere documented how to scrape for example an fgprof endpoint.

**Comment by brancz** [comment]
for completeness this is an example config:

```
debug_info:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"
  cache:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"

scrape_configs:
  - job_name: "default"
    scrape_interval: "3s"
    scrape_timeout: "4s"
    static_configs:
      - targets: [ '127.0.0.1:7070' ]
    profiling_config:
      pprof_config:
        fgprof:
          enabled: true
          path: /debug/pprof/fgprof
          delta: true
```
